import DLean.Axioms.DC
import DLean.Axioms.DI
import DLean.Axioms.DE
import DLean.Axioms.DG
import DLean.Axioms.DiffTerm
import DLean.Axioms.DL
import DLean.Axioms.DW
import DLean.Axioms.Refinement
import DLean.Axioms.Extended
import DLean.Axioms.DMP
